prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: "150m"
        memory: "400Mi"
      limits:
        cpu: "300m"
        memory: "800Mi"
    retention: 1d
alertmanager:
  enabled: false
grafana:
  enabled: true
  resources:
    requests:
      cpu: "50m"
      memory: "100Mi"
    limits:
      cpu: "200m"
      memory: "300Mi"
